name = "voicebot"
main = "functions/api/chat.ts"
compatibility_date = "2026-05-28"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "vasanthakumar"
database_id = "fba2b323-787c-48c5-ab49-148704690258"

